# Generated by Django 5.2.5 on 2025-08-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='summary_text',
            new_name='full_text',
        ),
    ]
