# Generated by Django 5.2.5 on 2025-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor_app', '0002_rename_summary_text_document_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_output_file',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tables_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
